backend:
  name: github
  repo: raellage/raellage-web

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }      
      - { name: description, label: Description }
      - { name: tags, label: Tags, widget: list  }
      - { name: body, label: Body, widget: markdown }
